version: '3.8'
services:
  php:
    build: ./php/
    container_name: php-infuse
    volumes:
      - ./www/html/:/var/www/html/
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-infuse
    links:
      - mysql
    environment:
      PMA_HOST: mysql-infuse
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80

  mysql:
    build: 
      context: ./mysql/
    container_name: mysql-infuse
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/sql/:/docker-entrypoint-initdb.d/
